id: IFF17F008
legacy_id: P005547
ocr_import_info:
  bdrc_scan_id: W1KG25056
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T12:59:35'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T14:05:06.793674+00:00'
last_modified: 2022-08-31 22:05:21.691004
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG25056
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG25056
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཡོངས་འཛིན་ཡེ་ཤེས་རྒྱལ་མཚན་གྱི་རྣམ་ཐར་ཐུབ་བསྟན་པདྨོ་རྒྱས་པའི་ཉིན་བྱེད།
  author: ཏཱ་ལའི་བླ་མ ༠༨་འཇམ་དཔལ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9586566015072533
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG25058:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG25058
      total_pages: 394
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG25058.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9586566015072533
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
