id: IFF17F008
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:02:05+00:00'
last_modified: '2022-06-08T04:49:45.811717+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25056
  title: ཡོངས་འཛིན་ཡེ་ཤེས་རྒྱལ་མཚན་གྱི་རྣམ་ཐར་ཐུབ་བསྟན་པདྨོ་རྒྱས་པའི་ཉིན་བྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    A4FC:
      image_group_id: I1KG25058
      title: ''
      total_pages: 394
      order: 1
      base_file: A4FC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
