id: P005547
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG25056
  title: ཡོངས་འཛིན་ཡེ་ཤེས་རྒྱལ་མཚན་གྱི་རྣམ་ཐར་ཐུབ་བསྟན་པདྨོ་རྒྱས་པའི་ཉིན་བྱེད།
  author: ''
  volumes:
    4da98e913fd145f9a915f9613734638d:
      image_group_id: I1KG25058
      title: ''
      volume_number: 1
      total_pages: 394
      base_file: v001.txt
